Translated images and documents into Simplified Chinese.
MoienTajik/AspNetCore-Developer-Roadmap pull request #164
Opened 2024-07-31 11:41 UTC by Warbin-Hub

I have updated the files aspnetcore-developer-roadmap.zh-Hans.png, aspnetcore-developer-roadmap.zh-Hans.xmind, and modified ReadMe.zh-Hans.md to the latest 2024 version.

2024-08-04 08:31 UTC, Warbin-Hub commented
I have updated the files aspnetcore-developer-roadmap.zh-Hans.png, aspnetcore-developer-roadmap.zh-Hans.xmind, and modified ReadMe.zh-Hans.md to the latest 2024 version.

2024-08-07 05:15 UTC, Warbin-Hub reviewed
I have updated the files aspnetcore-developer-roadmap.zh-Hans.png, aspnetcore-developer-roadmap.zh-Hans.xmind, and modified ReadMe.zh-Hans.md to the latest 2024 version.

2024-08-07 10:41 UTC, MoienTajik approved these changes
Thanks 🚀

2024-08-07 10:43 UTC, MoienTajik requested changes
Can you please compress the image?

2024-08-07 11:03 UTC, Warbin-Hub commented on ReadMe.zh-Hans.md
Added sponsor information in Simplified Chinese

2024-08-07 11:03 UTC, Warbin-Hub commented on aspnetcore-developer-roadmap.zh-Hans.png
Compressed the image size.

2024-08-07 11:03 UTC, Warbin-Hub commented on ReadMe.md
The ReadMe.md file was accidentally touched with a space, and I will restore it later.

2024-08-07 11:04 UTC, Warbin-Hub reviewed
Added sponsor information in Simplified Chinese and compressed the image size. The ReadMe.md file was accidentally touched with a space, and I will restore it later.

2024-08-07 11:08 UTC, Warbin-Hub commented
> Can you please compress the image?

I have completed the modifications and will continue to learn along the way. If I find any omissions later, I will make additions and corrections. Thank you for sharing.

2024-08-08 10:13 UTC, MoienTajik commented
Thanks for contribution @Warbin-Hub! 🚀

2024-08-08 10:13 UTC, merged